repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff-format
        args: [ --config=pyproject.toml ]
      - id: ruff
        args: [ --config=pyproject.toml ]
